// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNI5bhf9U_JbiCZFpwAEke2vc8avb-pEM',
    appId: '1:485208937193:web:641738f354a0bef5879678',
    messagingSenderId: '485208937193',
    projectId: 'pantrypal-3d506',
    authDomain: 'pantrypal-3d506.firebaseapp.com',
    storageBucket: 'pantrypal-3d506.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznjXEHWZ3Qr7ApgETwe35GNZhIgnC5aQ',
    appId: '1:485208937193:android:1ecb11f62ebb945e879678',
    messagingSenderId: '485208937193',
    projectId: 'pantrypal-3d506',
    storageBucket: 'pantrypal-3d506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbaqoVK3Urmrs937Gx-bpixfrQufZNTU',
    appId: '1:485208937193:ios:7148353c4950f5fb879678',
    messagingSenderId: '485208937193',
    projectId: 'pantrypal-3d506',
    storageBucket: 'pantrypal-3d506.firebasestorage.app',
    iosBundleId: 'com.example.pantryPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClbaqoVK3Urmrs937Gx-bpixfrQufZNTU',
    appId: '1:485208937193:ios:7148353c4950f5fb879678',
    messagingSenderId: '485208937193',
    projectId: 'pantrypal-3d506',
    storageBucket: 'pantrypal-3d506.firebasestorage.app',
    iosBundleId: 'com.example.pantryPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNI5bhf9U_JbiCZFpwAEke2vc8avb-pEM',
    appId: '1:485208937193:web:03a0ce8e7000ffaf879678',
    messagingSenderId: '485208937193',
    projectId: 'pantrypal-3d506',
    authDomain: 'pantrypal-3d506.firebaseapp.com',
    storageBucket: 'pantrypal-3d506.firebasestorage.app',
  );
}
